### ISSUE TITLE
Rcpp calls take vectors instead of scalars

### ISSUE THREAD

**Issue by erossiter** [erossiter/catSurv#10]
Right now probability takes "NumericVector theta, IntegerVector item" as arguments.  I need to look into this, but is it the case that Rcpp only allows for vectors?  Why are these arguments not restricted to scalars?  The next lines in the Rcpp function then feed the C++ program just the first element of each of these vectors.

We will want to clean this up so users aren't feeding the function a vector of theta values and expecting back results at each theta.

**Comment by alexjweil** [comment]
> but is it the case that Rcpp only allows for vectors?

Nope! Check out `obsInf`, which has the signature `obsInf(S4 catObj, double theta, int item)`. 

> Why are these arguments not restricted to scalars?

Looking back at the history of this, it looks like the function has taken a `NumericVector` and an `IntegerVector` as arguments since this repo was made; I suspect it's just the way it is for historical reasons.

**Comment by erossiter** [comment]
This is fixed on cpu branch.  Probability takes only a scalar for theta and item.
