### ISSUE TITLE
Move error check to top level in the call hierarchy: question > questionSet.answers.size() 

### ISSUE THREAD

**Issue by gmrhub** [erossiter/catSurv#20]
Currently it is/was In Estimator.cpp:
'std::vector<double> Estimator::probability(double theta, size_t question) {
  if (question > questionSet.answers.size() ) {
    throw std::domain_error("Must use a question number applicable to Cat object.");
  }'

**Comment by erossiter** [comment]
I think we want to leave the error here because probability() is a user-facing function, and we want an error present if the user puts something unreasonable.  Also, it is the only function (I think) that always takes 'question' as an argument, and probability is called by essentially all other functions, so the error will be caught regardless of what function is called.
